services:
  app:
    build: .
    container_name: flap-backend-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: flap-backend-db
    environment:
      POSTGRES_DB: flap-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata: